src/main/java/com/swyp/artego/domain/post/entity/Comment.java, src/main/java/com/swyp/artego/domain/post/entity/Item.java, src/main/java/com/swyp/artego/domain/post/repository/CommentRepository.java, src/main/java/com/swyp/artego/domain/post/repository/ItemRepository.java, src/main/java/com/swyp/artego/domain/user/entity/Commission.java, src/main/java/com/swyp/artego/domain/user/entity/Follow.java, src/main/java/com/swyp/artego/domain/user/entity/ItemEmoji.java, src/main/java/com/swyp/artego/domain/user/entity/Scrap.java, src/main/java/com/swyp/artego/domain/user/repository/CommissionRepository.java, src/main/java/com/swyp/artego/domain/user/repository/FollowRepository.java, src/main/java/com/swyp/artego/domain/user/repository/ItemEmojiRepository.java, src/main/java/com/swyp/artego/domain/user/repository/ScrapRepository.java
=> [All] feat: 엔티티 최초생성(0423기준)

.github/workflows/push.yml
- ssh 접속 후 script 실행 중 오류 발생 시 워크플로우도 실패 결과 반환하도록 함
- pure shell script(ssh script)에서 GitHub Actions 문법이 작동하도록 변수 선언
=> [GitHub Actions] 워크플로우 오류해결

build.gradle, src/main/java/com/swyp/artego/domain/comment/dto/request/CommentCreateRequest.java, src/main/java/com/swyp/artego/domain/comment/dto/response/CommentInfoResponse.java, src/main/java/com/swyp/artego/domain/comment/entity/Comment.java, src/main/java/com/swyp/artego/domain/comment/service/CommentServiceImpl.java, src/main/java/com/swyp/artego/domain/item/component/MultipartJackson2HttpMessageConverter.java, src/main/java/com/swyp/artego/domain/item/controller/ItemController.java, src/main/java/com/swyp/artego/domain/item/dto/request/ItemCreateRequest.java, src/main/java/com/swyp/artego/domain/item/dto/response/ItemCreateResponse.java, src/main/java/com/swyp/artego/domain/item/dto/response/ItemInfoResponse.java, src/main/java/com/swyp/artego/domain/item/entity/Item.java, src/main/java/com/swyp/artego/domain/item/enums/CategoryType.java, src/main/java/com/swyp/artego/domain/item/service/ItemService.java, src/main/java/com/swyp/artego/domain/item/service/ItemServiceImpl.java, src/main/java/com/swyp/artego/global/common/code/ErrorCode.java, src/main/java/com/swyp/artego/global/common/code/SuccessCode.java, src/main/java/com/swyp/artego/global/config/NCPStorageConfig.java, src/main/java/com/swyp/artego/global/excpetion/GlobalExceptionHandler.java, src/main/java/com/swyp/artego/global/file/controller/FileController.java, src/main/java/com/swyp/artego/global/file/controller/FileViewController.java, src/main/java/com/swyp/artego/global/file/dto/request/FileDeleteRequest.java, src/main/java/com/swyp/artego/global/file/dto/response/FileResponse.java, src/main/java/com/swyp/artego/global/file/dto/response/FileUploadResponse.java, src/main/java/com/swyp/artego/global/file/dto/response/FileUploadResponseExample.java, src/main/java/com/swyp/artego/global/file/service/FileService.java, src/main/resources/application-local.yml, src/main/resources/application-prod.yml, src/main/resources/application.yml, src/main/resources/templates/upload.html, src/test/java/com/swyp/artego/global/file/service/FileServiceTest.java
- 다중 파일 업로드 API 구현
- 다중 파일 업로드 API 단위 테스트
- 단일 파일 업로드 API 구현
- 단일 파일 업로드 API 단위 테스트
- Exception 발생 단위 테스트
- 작품 생성 API 구현
- ErrorCode 내 잘못된 status 및 메시지 수정
- GlobalExceptionHandler의 분기 로직 개선 및 신규 핸들러 추가
- BusinessExceptionHandler HttpStatus 반환 로직을 ErrorCode 기준으로 정리
- GlobalExceptionHandler 내 잘못된 HttpStatus 수정
=> Feat/#11 + Refactor Excpetions

src/main/java/com/swyp/artego/domain/item/enums/SortType.java, src/main/java/com/swyp/artego/global/dummy/controller/DummyItemController.java, src/main/java/com/swyp/artego/global/dummy/service/DummyItemService.java, src/main/java/com/swyp/artego/global/file/controller/FileController.java, src/main/resources/application-local.yml, src/main/resources/application-prod.yml
- 아이템 더미데이터 추가 (JdbcTemplate BatchUpdate)
=> [아이템] 더미데이터 추가 API

build.gradle, src/main/java/com/swyp/artego/domain/item/dto/request/ItemCreateRequest.java, src/main/java/com/swyp/artego/domain/item/dto/response/ItemCreateResponse.java, src/main/java/com/swyp/artego/domain/item/dto/response/ItemInfoResponse.java, src/main/java/com/swyp/artego/domain/item/entity/Item.java, src/main/java/com/swyp/artego/domain/item/enums/SortType.java, src/main/java/com/swyp/artego/domain/item/repository/ItemRepository.java, src/main/java/com/swyp/artego/domain/item/repository/ItemSearchRepositoryImpl.java, src/main/java/com/swyp/artego/global/auth/oauth/model/AuthUser.java, src/main/java/com/swyp/artego/global/common/code/ErrorCode.java, src/main/java/com/swyp/artego/global/common/service/ItemBatchService.java, src/main/java/com/swyp/artego/global/dummy/controller/DummyItemController.java, src/main/java/com/swyp/artego/global/dummy/service/DummyItemService.java, src/main/java/com/swyp/artego/global/excpetion/GlobalExceptionHandler.java, src/main/java/com/swyp/artego/global/file/controller/FileController.java, src/main/resources/application-local.yml, src/main/resources/application-prod.yml, src/main/resources/application.yml, src/test/java/com/swyp/artego/domain/item/controller/ItemControllerTest.java
- controller test 작성
- 성공
- multipart file 이 max 값 초과하는 경우
- multipart file 누락 & 이 경우 예외 핸들러 추가
- 작품 사이즈 검증 로직 (+구현)
참고
- [item] secret 필드 삭제. statusType 사용.
=> [Item] 생성 API - controller 테스트

src/main/java/com/swyp/artego/domain/item/dto/request/ItemSearchRequest.java, src/main/java/com/swyp/artego/domain/item/entity/Item.java, src/main/java/com/swyp/artego/domain/item/repository/ItemSearchRepositoryImpl.java, src/main/java/com/swyp/artego/global/dummy/controller/DummyAuthController.java, src/main/java/com/swyp/artego/global/dummy/dto/DummyOAuth2Response.java, src/main/java/com/swyp/artego/global/dummy/service/DummyItemService.java, src/main/resources/application-prod.yml, src/main/resources/application.yml
- fix: 프론트 요구에 따라 페이지 번호를 1부터 시작하도록 수정
- fix: 더미 아이템 생성 시 상태값을 StatusType.OPEN으로 고정
- [User] feat : 더미 유저 생성 추가
=> fix: 프론트 요구에 따라 페이지 번호를 1부터 시작하도록 수정

src/main/resources/application-prod.yml
=> fix: yml indent 오류 수정

src/main/java/com/swyp/artego/domain/user/controller/UserController.java, src/main/java/com/swyp/artego/domain/user/dto/response/UserInfoSimpleResponse.java, src/main/java/com/swyp/artego/domain/user/entity/User.java, src/main/java/com/swyp/artego/domain/user/service/UserService.java, src/main/java/com/swyp/artego/domain/user/service/UserServiceImpl.java, src/main/java/com/swyp/artego/global/auth/oauth/controller/AuthController.java, src/main/java/com/swyp/artego/global/auth/oauth/handler/LoginSuccessHandler.java
=> fix : 소셜로그인 프론트와 연동

src/main/java/com/swyp/artego/domain/follow/controller/FollowController.java, src/main/java/com/swyp/artego/domain/follow/dto/response/FollowPreviewListResponse.java, src/main/java/com/swyp/artego/domain/follow/dto/response/FollowPreviewResponse.java, src/main/java/com/swyp/artego/domain/follow/repository/FollowRepository.java, src/main/java/com/swyp/artego/domain/follow/service/FollowService.java, src/main/java/com/swyp/artego/domain/follow/service/FollowServiceImpl.java, src/main/java/com/swyp/artego/domain/itemEmoji/controller/ItemEmojiController.java, src/main/java/com/swyp/artego/domain/itemEmoji/dto/request/ItemEmojiCreateRequest.java, src/main/java/com/swyp/artego/domain/itemEmoji/repository/ItemEmojiRepository.java, src/main/java/com/swyp/artego/domain/itemEmoji/service/ItemEmojiService.java, src/main/java/com/swyp/artego/domain/itemEmoji/service/ItemEmojiServiceImpl.java, src/main/java/com/swyp/artego/global/common/code/ErrorCode.java, src/main/java/com/swyp/artego/global/common/service/ItemBatchService.java, src/main/java/com/swyp/artego/global/dummy/service/DummyItemService.java, src/main/resources/application-local.yml, src/main/resources/application-prod.yml
- 팔로우 등록, 취소, 프리뷰 (추가)
- 반응 등록, 취소 (추가)
- 배치 N+1 문제 해결 (패치 조인)(아이템 조회 시 유저에서 발생)
- 배치 더미 유저 데이터 이미지 추가
=> [팔로우,반응] feat : 등록,취소,프리뷰  

src/main/java/com/swyp/artego/domain/item/enums/SortType.java, src/main/java/com/swyp/artego/domain/item/repository/ItemSearchRepositoryImpl.java
- SCRAP_ITEM_RECENT 정렬 타입 추가
- 로그인 유저가 스크랩한 아이템을 아이템 생성일 기준으로 최신순으로 정렬
=> [Item] feat: 스크랩한 아이템을 아이템 생성일 기준 최신순으로 정렬 기능 추가

src/main/java/com/swyp/artego/domain/comment/controller/CommentController.java, src/main/java/com/swyp/artego/domain/item/controller/ItemController.java, src/main/java/com/swyp/artego/global/file/controller/FileController.java, src/main/java/com/swyp/artego/global/file/dto/request/FileDeleteRequest.java, src/main/java/com/swyp/artego/global/file/dto/response/FileUploadResponse.java, src/main/java/com/swyp/artego/global/file/dto/response/FileUploadResponseExample.java, src/main/java/com/swyp/artego/global/file/service/FileService.java, src/test/java/com/swyp/artego/global/file/service/FileServiceTest.java
=> [File] 삭제한 API 복원

src/main/java/com/swyp/artego/domain/follow/controller/FollowController.java, src/main/java/com/swyp/artego/domain/follow/dto/response/FollowPreviewResponse.java, src/main/java/com/swyp/artego/domain/follow/dto/response/FollowedArtistResponse.java, src/main/java/com/swyp/artego/domain/follow/dto/response/FollowedArtistsResponse.java, src/main/java/com/swyp/artego/domain/follow/repository/FollowRepository.java, src/main/java/com/swyp/artego/domain/follow/repository/FollowSearchRepository.java, src/main/java/com/swyp/artego/domain/follow/repository/FollowSearchRepositoryImpl.java, src/main/java/com/swyp/artego/domain/follow/service/FollowService.java, src/main/java/com/swyp/artego/domain/follow/service/FollowServiceImpl.java, src/main/java/com/swyp/artego/domain/item/controller/ItemController.java, src/main/java/com/swyp/artego/domain/item/dto/response/ItemSearchResponse.java, src/main/java/com/swyp/artego/domain/scrap/controller/ScrapController.java, src/main/java/com/swyp/artego/domain/scrap/repository/ScrapRepository.java, src/main/java/com/swyp/artego/domain/scrap/service/ScrapService.java, src/main/java/com/swyp/artego/domain/scrap/service/ScrapServiceImpl.java, src/main/java/com/swyp/artego/domain/user/controller/UserController.java, src/main/java/com/swyp/artego/domain/user/entity/User.java, src/main/java/com/swyp/artego/global/dummy/controller/DummyAuthController.java
- 팔로잉 전체 목록 조회
- 필요없는 컨트롤러 삭제
- 스크랩 생성, 취소 추가 (중복까지 고려)
=> [팔로우,스크랩] feat : 팔로잉 전체목록 , 스크랩 생성, 취소

src/main/java/com/swyp/artego/domain/follow/dto/response/FollowPreviewResponse.java, src/main/java/com/swyp/artego/domain/item/dto/request/ItemSearchRequest.java, src/main/java/com/swyp/artego/domain/item/repository/ItemSearchRepositoryImpl.java, src/main/java/com/swyp/artego/domain/user/controller/UserController.java, src/main/java/com/swyp/artego/domain/user/dto/response/UserInfoSimpleResponse.java, src/main/java/com/swyp/artego/domain/user/entity/User.java, src/main/java/com/swyp/artego/domain/user/repository/UserRepository.java, src/main/java/com/swyp/artego/domain/user/service/UserService.java, src/main/java/com/swyp/artego/domain/user/service/UserServiceImpl.java, src/main/java/com/swyp/artego/global/auth/oauth/service/AuthService.java, src/main/java/com/swyp/artego/global/dummy/controller/DummyAuthController.java, src/main/java/com/swyp/artego/global/dummy/service/DummyItemService.java, src/main/resources/application-prod.yml
- 더미 로그인 버그 수정
- 유저 필드 추가
- 닉네임(유저 + # + 랜덤6자)
=> fix : 테스트 로그인 기능 수정, 유저 필드 추가

src/main/java/com/swyp/artego/domain/item/dto/request/ItemSearchRequest.java, src/main/java/com/swyp/artego/domain/user/controller/UserController.java, src/main/java/com/swyp/artego/domain/user/dto/response/ArtistDetailInfoResponse.java, src/main/java/com/swyp/artego/domain/user/entity/User.java, src/main/java/com/swyp/artego/domain/user/enums/Role.java, src/main/java/com/swyp/artego/domain/user/service/UserService.java, src/main/java/com/swyp/artego/domain/user/service/UserServiceImpl.java, src/main/java/com/swyp/artego/global/common/service/UserBatchService.java, src/main/java/com/swyp/artego/global/dummy/service/DummyItemService.java, src/main/resources/application-prod.yml
- 작가 세부 정보 조회
- 작가 (작품,스크랩,팔로워,리액션)관련 count -> 10분간격 업데이트
=> feat : 작가 세부 정보 조회

src/main/java/com/swyp/artego/domain/user/controller/UserController.java, src/main/java/com/swyp/artego/domain/user/service/UserService.java, src/main/java/com/swyp/artego/domain/user/service/UserServiceImpl.java, src/main/resources/application-local.yml, src/main/resources/application-prod.yml
=> fix : 작가 세부 정보 조회

src/main/java/com/swyp/artego/domain/item/controller/ItemController.java, src/main/java/com/swyp/artego/domain/item/dto/response/ItemFindByItemIdResponse.java, src/main/java/com/swyp/artego/domain/item/service/ItemService.java, src/main/java/com/swyp/artego/domain/item/service/ItemServiceImpl.java, src/main/java/com/swyp/artego/domain/scrap/repository/ScrapRepository.java
추가된 필드
- artist.id
- viewer.isScrapped
- viewer.isOwner
=> Feat/#81: 조회 API 응답 필드 추가

src/main/java/com/swyp/artego/domain/comment/dto/response/MyCommentActivityResponse.java, src/main/java/com/swyp/artego/domain/comment/dto/response/MyCommentActivityResultResponse.java, src/main/java/com/swyp/artego/domain/comment/repository/CommentQueryRepositoryImpl.java, src/main/java/com/swyp/artego/domain/user/controller/UserController.java, src/main/java/com/swyp/artego/domain/user/dto/request/UserUpdateRequest.java, src/main/java/com/swyp/artego/domain/user/dto/response/UserInfoSimpleResponse.java, src/main/java/com/swyp/artego/domain/user/dto/response/UserLoginInfoResponse.java, src/main/java/com/swyp/artego/domain/user/service/UserService.java, src/main/java/com/swyp/artego/domain/user/service/UserServiceImpl.java
- 유저 프로필 수정 기능 추가
- 마이페이지에서 보여주는 댓글 목록 응답 값 수정, SOFT 삭제도 보여지게 변경
- 작가 프로필 수정 기능 엔드포인트 수정
=> feat : 유저 프로필 수정, 댓글 목록 수정

src/main/java/com/swyp/artego/domain/follow/repository/FollowRepository.java, src/main/java/com/swyp/artego/domain/item/dto/response/ItemFindByItemIdResponse.java, src/main/java/com/swyp/artego/domain/item/service/ItemServiceImpl.java
- isFollowing 추가
- isFollowing, isScrapped 정책 수정.
- 로그인을 안한 사용자의 요청에도 false를 리턴한다. 기존엔 null 리턴.
=> Feat/#81 [Item] 조회 API 작가 팔로우 반환 여부 추가

src/main/java/com/swyp/artego/domain/item/dto/response/ItemFindByItemIdResponse.java
=> [Item] feat: 조회 API 작가 실명이 아닌 닉네임 반환하도록 변경

src/main/java/com/swyp/artego/domain/comment/repository/CommentQueryRepositoryImpl.java, src/main/java/com/swyp/artego/global/auth/oauth/handler/CustomAccessDeniedHandler.java, src/main/java/com/swyp/artego/global/common/code/ErrorCode.java, src/main/java/com/swyp/artego/global/config/SecurityConfig.java, src/main/java/com/swyp/artego/global/dummy/controller/DummyAuthController.java
=> feat: 필터 추가

src/main/java/com/swyp/artego/global/auth/oauth/controller/AuthController.java, src/main/java/com/swyp/artego/global/auth/oauth/service/AuthService.java
=> fix : 소셜로그인 기능

src/main/java/com/swyp/artego/domain/artistApply/service/ArtistApplyServiceImpl.java, src/main/java/com/swyp/artego/domain/notification/controller/NotificationController.java, src/main/java/com/swyp/artego/domain/notification/enums/NotificationType.java, src/main/java/com/swyp/artego/domain/notification/repository/NotificationRepository.java, src/main/java/com/swyp/artego/domain/notification/service/NotificationService.java, src/main/java/com/swyp/artego/domain/notification/service/NotificationServiceImpl.java, src/main/java/com/swyp/artego/global/config/SecurityConfig.java, src/main/resources/application-local.yml
1. SSE 연결 비동기로 변경
2. 안읽은 알림 모두 읽음으로 변경 기능 추가
3. 작가 승인 시 유저에게 알림 기능 추가
=> [Notification] fix: 커넥션 풀 누수 해결

src/main/java/com/swyp/artego/global/common/service/ItemBatchService.java, src/main/java/com/swyp/artego/global/common/service/UserBatchService.java, src/main/java/com/swyp/artego/global/dummy/service/DummyItemService.java
- 기존에는 더미 아이템 생성 시 유저의 ROLE이 기본값인 USER로 설정되어, 
- 작가 상세정보 페이지 접근 시 미권한 오류가 발생하였습니다.
- 이에 따라 더미 유저 생성 시 ROLE을 ARTIST로 설정하여 
- 작가 관련 API에서 권한 문제 없이 정상 동작하도록 수정하였습니다.
=> [DummyUser] fix: 더미 아이템 생성 시 만든 작가 ROLE.ARTIST로 수정
